name: Deploy PropertyWala_Server 
on: 
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t neam6009/propertywala_backend  . 
      - name: Publish Image to docker hub
        run: docker push neam6009/propertywala_backend:latest 
 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull neam6009/propertywala_backend 
      - name: Delete old container
        run: docker rm -f propertywala_backend-container 
      - name: Run Docker Container
        run: docker run -d -p 3003:3003 --name propertywala_backend-container neam6009/propertywala_backend 